Repository actualbudget/actual-server, pull requests merged in 2023-01, with the labels that each got.

#56 Migrate to yarn v3.2.1
  .gitignore
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ✅ Approved

#91 :white_check_mark: (adding jest for unit/integration tests)
  .eslintrc.js
  .github/workflows/test.yml
  .gitignore
  app-sync.test.js
  jest.config.json
  jest.setup.js
  load-config.js
  package.json
  yarn.lock
Labels: ✅ Approved

#89 Allow config.json to contain a partial config
  load-config.js
Labels: needs-testing, ✅ Approved

#102 fix: :lock: Password change now invalidates old token
  app-account.js
Labels: needs-testing, 🔍 Ready for Review, ✅ Approved

#109 fix: listen also listen on ipv6 addresses
  load-config.js
Labels: ✅ Approved
