Repository actualbudget/actual-server, pull requests merged in 2023-03, with the labels that each got.

#74 Backend integration with Nordigen - account sync
  .gitignore
  babel.config.json
  jest.config.json
  package.json
  src/app-nordigen/README.md
  src/app-nordigen/app-nordigen.js
  src/app-nordigen/bank-factory.js
  src/app-nordigen/banks/bank.interface.ts
  src/app-nordigen/banks/ing-pl-ingbplpw.js
  src/app-nordigen/banks/integration-bank.js
  src/app-nordigen/banks/mbank-retail-brexplpw.js
  src/app-nordigen/banks/sandboxfinance-sfin0000.js
  src/app-nordigen/banks/tests/ing-pl-ingbplpw.spec.js
  src/app-nordigen/banks/tests/integration-bank.spec.js
  src/app-nordigen/banks/tests/mbank-retail-brexplpw.spec.js
  src/app-nordigen/banks/tests/sandboxfinance-sfin0000.spec.js
  src/app-nordigen/errors.js
  src/app-nordigen/nordigen-node.types.ts
  src/app-nordigen/nordigen.types.ts
  src/app-nordigen/services/nordigen-service.js
  src/app-nordigen/services/tests/fixtures.js
  src/app-nordigen/services/tests/nordigen-service.spec.js
  src/app-nordigen/tests/bank-factory.spec.js
  src/app-nordigen/tests/utils.spec.js
  src/app-nordigen/util/handle-error.js
  src/app-nordigen/utils.js
  src/app.js
  src/config-types.ts
  tsconfig.json
  yarn.lock
Labels: ✅ Approved

#121 Update the :edge images to use the very latest web UI version
  .dockerignore
  .github/workflows/docker-edge.yml
  .github/workflows/docker-release.yml
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarnrc.yml
  Dockerfile
  Dockerfile.alpine
  docker/edge-alpine.Dockerfile
  docker/edge-ubuntu.Dockerfile
  docker/stable-alpine.Dockerfile
  docker/stable-ubuntu.Dockerfile
  src/account-db.js
  src/load-config.js
  src/sql/account.sql
  src/sql/messages.sql
  src/sync-simple.js
Labels: ✅ Approved

#145 :sparkles: (bank-sync) expose available banks via an endpoint
  src/app-nordigen/app-nordigen.js
Labels: ✅ Approved

#146 :arrow_up: upgrade yarn to v3.4.1 and add interactive-tools plugin
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.2.1.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  package.json
Labels: ✅ Approved

#147 Improve edge image build times
  .github/workflows/docker-edge.yml
  docker/edge-alpine.Dockerfile
  docker/edge-ubuntu.Dockerfile
Labels: ✅ Approved

#144 :sparkles: (bank-sync) meaningful default balance calculation
  src/app-nordigen/app-nordigen.js
  src/app-nordigen/banks/integration-bank.js
  src/app-nordigen/banks/tests/integration-bank.spec.js
  src/app-nordigen/services/nordigen-service.js
  src/app-nordigen/services/tests/nordigen-service.spec.js
  yarn.lock
Labels: ✅ Approved

#148 :rotating_light: adding trailing commas everywhere
  .eslintrc.cjs
  .prettierrc.json
  migrations/1632571489012_remove_cache.js
  package.json
  src/app-account.js
  src/app-nordigen/app-nordigen.js
  src/app-nordigen/banks/bank.interface.ts
  src/app-nordigen/banks/ing-pl-ingbplpw.js
  src/app-nordigen/banks/integration-bank.js
  src/app-nordigen/banks/mbank-retail-brexplpw.js
  src/app-nordigen/banks/sandboxfinance-sfin0000.js
  src/app-nordigen/banks/tests/ing-pl-ingbplpw.spec.js
  src/app-nordigen/banks/tests/integration-bank.spec.js
  src/app-nordigen/banks/tests/mbank-retail-brexplpw.spec.js
  src/app-nordigen/banks/tests/sandboxfinance-sfin0000.spec.js
  src/app-nordigen/errors.js
  src/app-nordigen/nordigen.types.ts
  src/app-nordigen/services/nordigen-service.js
  src/app-nordigen/services/tests/fixtures.js
  src/app-nordigen/services/tests/nordigen-service.spec.js
  src/app-nordigen/tests/utils.spec.js
  src/app-nordigen/utils.js
  src/app-sync.js
  src/app-sync.test.js
  src/app.js
  src/load-config.js
  src/sync-simple.js
  src/util/validate-user.js
Labels: ✅ Approved

#154 :bookmark: (23.3.0) experimental bank-sync, maintenance, fixes
  package.json
  yarn.lock
Labels: ✅ Approved

#155 🔖 (23.3.1) fix nordigen usage in fly.io
  package.json
  src/app-nordigen/services/nordigen-service.js
  src/config-types.ts
  src/load-config.js
Labels: ✅ Approved

#156 Re-generate nordigen token
  package.json
  src/app-nordigen/services/nordigen-service.js
  yarn.lock
Labels: ✅ Approved

#157 Don’t make Dockerfile a symlink
  Dockerfile
Labels: ✅ Approved

#160 :bug: (nordigen) close window when opening /nordigen/link path
  src/app-nordigen/app-nordigen.js
  src/app-nordigen/link.html
Labels: ✅ Approved

#161 Update README.md
  README.md
Labels: ✅ Approved

#162 :sparkles: (nordigen) add status endpoint for checking status
  src/app-nordigen/app-nordigen.js
  src/app-nordigen/services/nordigen-service.js
Labels: ✅ Approved

#163 :bug: (nordigen) add currency to account name
  src/app-nordigen/banks/integration-bank.js
  src/app-nordigen/banks/tests/integration-bank.spec.js
Labels: 🔍 Ready for Review

#140 Remove year from the LICENSE
  LICENSE.txt
Labels: ✅ Approved

#164 :bookmark: (23.3.2) nordigen fixes
  package.json
  yarn.lock
Labels: ✅ Approved

#165 Add support for automatically generating release notes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-release-notes.yml
  .github/workflows/generate-release-notes.yml
  upcoming-release-notes/165.md
  upcoming-release-notes/README.md
Labels: ✅ Approved

#168 :sparkles: (bank-sync) expose demo bank in the get-banks endpoint
  src/app-nordigen/app-nordigen.js
  upcoming-release-notes/168.md
Labels: ✅ Approved

#167 Report parse issues for config.json in default location
  src/load-config.js
  upcoming-release-notes/167.md
Labels: ✅ Approved

#166 (nordigen) Include hashed IBAN in get-accounts and transactions endpoints
  src/app-nordigen/app-nordigen.js
  src/app-nordigen/banks/ing-pl-ingbplpw.js
  src/app-nordigen/banks/integration-bank.js
  src/app-nordigen/banks/mbank-retail-brexplpw.js
  src/app-nordigen/banks/sandboxfinance-sfin0000.js
  src/app-nordigen/banks/tests/ing-pl-ingbplpw.spec.js
  src/app-nordigen/banks/tests/integration-bank.spec.js
  src/app-nordigen/banks/tests/mbank-retail-brexplpw.spec.js
  src/app-nordigen/banks/tests/sandboxfinance-sfin0000.spec.js
  src/app-nordigen/nordigen.types.ts
  src/app-nordigen/services/nordigen-service.js
  src/app-nordigen/services/tests/nordigen-service.spec.js
  src/util/hash.js
  upcoming-release-notes/166.md
Labels: 🔍 Ready for Review, ✅ Approved

#172 Stream file without loading to memory in /download-user-file
  src/app-sync.js
  src/app-sync.test.js
  upcoming-release-notes/172.md
Labels: ✅ Approved

#150 Update docker-compose.yml
  docker-compose.yml
  upcoming-release-notes/150.md
Labels: 🔍 Ready for Review

#141 Add linux/arm/v7 to the list of platforms for the Docker image
  .github/workflows/docker-edge.yml
  .github/workflows/docker-release.yml
  README.md
  upcoming-release-notes/141.md
Labels: 🔍 Ready for Review

#175 :sparkles: New Docker Hub org in CI and README
  .github/workflows/docker-edge.yml
  .github/workflows/docker-release.yml
  README.md
  docker-compose.yml
  upcoming-release-notes/175.md
Labels: 🔍 Ready for Review
