Repository actualbudget/actual-server, pull requests merged in 2023-06, with the labels that each got.

#208 Migrate to combined release notes action from main repo
  .github/workflows/check-release-notes.yml
  .github/workflows/generate-release-notes.yml
  .github/workflows/release-notes.yml
  upcoming-release-notes/208.md
Labels: ✅ Approved

#207 :bookmark: (23.6.0) category hiding and filters for reports
  package.json
  upcoming-release-notes/204.md
  upcoming-release-notes/208.md
  yarn.lock
Labels: ✅ Approved

#215 Update README.md
  README.md
Labels: 🔍 Ready for Review, ✅ Approved

#216 Update “how it works” link
  README.md
Labels: ✅ Approved

#217 Contributing readme link update
  README.md
Labels: ✅ Approved

#214 Add a health check script
  package.json
  src/scripts/health-check.js
  upcoming-release-notes/214.md
Labels: 🔍 Ready for Review

#218 :recycle: (crdt) use actual-app/crdt package instead of api
  package.json
  src/app-sync.js
  src/sync-simple.js
  upcoming-release-notes/218.md
  yarn.lock
Labels: ✅ Approved
