Repository actualbudget/actual-server, pull requests merged in 2024-06, with the labels that each got.

#368 :bookmark: (24.6.0)
  package.json
  upcoming-release-notes/312.md
  upcoming-release-notes/346.md
  upcoming-release-notes/349.md
  upcoming-release-notes/350.md
  upcoming-release-notes/355.md
  upcoming-release-notes/357.md
  yarn.lock
Labels: 🔍 Ready for Review

#366 Ignore coverage folder in the coverage report.
  jest.config.json
  upcoming-release-notes/366.md
Labels: 🔍 Ready for Review, ✅ Approved

#362 Refactor GoCardless bank code to avoid duplication
  src/app-gocardless/banks/american-express-aesudef1.js
  src/app-gocardless/banks/bankinter-bkbkesmm.js
  src/app-gocardless/banks/belfius_gkccbebb.js
  src/app-gocardless/banks/bnp-be-gebabebb.js
  src/app-gocardless/banks/danskebank-dabno22.js
  src/app-gocardless/banks/ing-ingddeff.js
  src/app-gocardless/banks/ing-pl-ingbplpw.js
  src/app-gocardless/banks/mbank-retail-brexplpw.js
  src/app-gocardless/banks/norwegian-xx-norwnok1.js
  src/app-gocardless/banks/sandboxfinance-sfin0000.js
  src/app-gocardless/banks/seb-kort-bank-ab.js
  src/app-gocardless/banks/seb-privat.js
  src/app-gocardless/banks/sparnord-spnodk22.js
  src/app-gocardless/banks/spk-karlsruhe-karsde66.js
  src/app-gocardless/banks/spk-marburg-biedenkopf-heladef1mar.js
  upcoming-release-notes/362.md
Labels: 🔍 Ready for Review, ✅ Approved

#367 Add GoCardless banks to the bank factory test suite.
  src/app-gocardless/bank-factory.js
  src/app-gocardless/tests/bank-factory.spec.js
  upcoming-release-notes/367.md
Labels: ✅ Approved

#359 Grab payee name for Abanca gocardless integration
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/abanca-caglesmm.js
  src/app-gocardless/banks/tests/abanca-caglesmm.spec.js
  upcoming-release-notes/359.md
Labels: ⚠️ Changes requested

#360 Add bank handler for `VIRGIN_NRNBGB22` (Virgin Money)
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/tests/virgin_nrnbgb22.spec.js
  src/app-gocardless/banks/virgin_nrnbgb22.js
  upcoming-release-notes/360.md
Labels: 🔍 Ready for Review

#378 :arrow_up: upgrade dependency tree to solve CVE-2023-42282
  package.json
  upcoming-release-notes/378.md
  yarn.lock
Labels: ✅ Approved
