Repository actualbudget/actual-server, pull requests merged in 2024-08, with the labels that each got.

#407 [WIP] Update mbank-retail-brexplpw.js
  src/app-gocardless/banks/mbank-retail-brexplpw.js
  upcoming-release-notes/407.md
Labels: :construction: WIP

#408 :bookmark: (24.8.0)
  package.json
  upcoming-release-notes/353.md
  upcoming-release-notes/385.md
  upcoming-release-notes/386.md
  upcoming-release-notes/388.md
  upcoming-release-notes/389.md
  upcoming-release-notes/390.md
  upcoming-release-notes/391.md
  upcoming-release-notes/396.md
  upcoming-release-notes/397.md
  upcoming-release-notes/400.md
  upcoming-release-notes/401.md
  upcoming-release-notes/402.md
  upcoming-release-notes/403.md
  upcoming-release-notes/405.md
  upcoming-release-notes/406.md
  upcoming-release-notes/407.md
  yarn.lock
Labels: :white_check_mark: Approved

#358 Add gocardless support for Berliner Sparkasse (Germany)
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/berliner_sparkasse_beladebexxx.js
  upcoming-release-notes/358.md
Labels: :white_check_mark: Approved

#409 Fix crash when SimpleFIN JSON data is bad.
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/409.md
Labels: :white_check_mark: Approved

#410 Stop server crashing when SimpleFIN is down.
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/410.md
Labels: :white_check_mark: Approved

#412 Show better error if SimpleFIN account cant be found.
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/412.md
Labels: :white_check_mark: Approved

#413 Return early from SimpleFIN /transactions if the account needs attention
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/413.md
Labels: :white_check_mark: Approved

#418 Add SANTANDER_BSCHESMM to banks with limited history
  src/app-gocardless/bank-factory.js
  upcoming-release-notes/418.md
Labels: :mag: Ready for review

#421 [Maintenance] improve testing utils and add delete-user-file test
  package.json
  src/app-sync.js
  src/app-sync.test.js
  src/run-migrations.js
  upcoming-release-notes/421.md
Labels: :white_check_mark: Approved

#422 [Maintenance] refactor user validation into middleware
  package.json
  src/app-account.js
  src/app-gocardless/app-gocardless.js
  src/app-secrets.js
  src/app-sync.js
  src/util/error-middleware.js
  src/util/middlewares.js
  upcoming-release-notes/422.md
Labels: :mag: Ready for review

#430 add stale workflow update from actual
  .github/workflows/stale.yml
  upcoming-release-notes/430.md
Labels: :mag: Ready for review

#423 add integration tests for the `/sync` endpoint
  src/app-sync.js
  src/app-sync.test.js
  upcoming-release-notes/423.md
Labels: :white_check_mark: Approved

#427 fix payee name selection based on the amount
  src/util/payee-name.js
  upcoming-release-notes/427.md
Labels: :white_check_mark: Approved

#425 add more tests for app-sync.js
  src/app-sync.js
  src/app-sync.test.js
  upcoming-release-notes/425.md
Labels: :white_check_mark: Approved

#435 🧹 remove unused accountMetadata GoCardless API call on sync
  src/app-gocardless/app-gocardless.js
  src/app-gocardless/services/gocardless-service.js
  src/app-gocardless/services/tests/gocardless-service.spec.js
  upcoming-release-notes/435.md
Labels: :white_check_mark: Approved

#436 🧹 optimise GoCardless bank sync to use fewer api calls
  src/app-gocardless/app-gocardless.js
  src/app-gocardless/services/gocardless-service.js
  upcoming-release-notes/436.md
Labels: :white_check_mark: Approved

#428 Fallback creditorName to remittanceInformationUnstructured in BANKINTER_BKBKESMM
  src/app-gocardless/banks/bankinter-bkbkesmm.js
  upcoming-release-notes/428.md
Labels: :white_check_mark: Approved

#429 Prevent account fallback if name is defined in formatPayeeName
  src/util/payee-name.js
  upcoming-release-notes/429.md
Labels: :white_check_mark: Approved

#441 Update bank-factory.js
  src/app-gocardless/bank-factory.js
  upcoming-release-notes/441.md
Labels: :white_check_mark: Approved
