Repository actualbudget/actual-server, pull requests merged in 2024-10, with the labels that each got.

#449 [WIP] Add "Banco ActivoBank" (PT) to list of banks with limited history
  src/app-gocardless/bank-factory.js
  upcoming-release-notes/449.md
Labels: :construction: WIP

#471 :wrench: update issue links to point to discord & main actual repo
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  upcoming-release-notes/471.md
Labels: :white_check_mark: Approved

#472 :bookmark: (24.10.0)
  package.json
  upcoming-release-notes/384.md
  upcoming-release-notes/445.md
  upcoming-release-notes/448.md
  upcoming-release-notes/449.md
  upcoming-release-notes/451.md
  upcoming-release-notes/452.md
  upcoming-release-notes/454.md
  upcoming-release-notes/455.md
  upcoming-release-notes/459.md
  upcoming-release-notes/465.md
  upcoming-release-notes/471.md
  yarn.lock
Labels: :white_check_mark: Approved

#475 :bookmark: (24.10.1)
  package.json
  yarn.lock
Labels: :mag: Ready for review

#474 fix: Sabadell Bank regression, missing date field during normalization
  src/app-gocardless/banks/bancsabadell-bsabesbbb.js
  src/app-gocardless/banks/tests/bancsabadell-bsabesbbb.spec.js
  upcoming-release-notes/474.md
Labels: :white_check_mark: Approved

#480 Allowing data dir to be overridden
  src/load-config.js
  upcoming-release-notes/480.md
Labels: :mag: Ready for review

#481 Add Fineco to banks with limited history
  src/app-gocardless/bank-factory.js
  upcoming-release-notes/481.md
Labels: :white_check_mark: Approved

#478 refactor: set correct log level
  src/app-gocardless/banks/integration-bank.js
  src/app-gocardless/banks/tests/integration-bank.spec.js
  upcoming-release-notes/478.md
Labels: :white_check_mark: Approved

#473 Add "N26" to banks with limited history
  src/app-gocardless/bank-factory.js
  upcoming-release-notes/473.md
Labels: :white_check_mark: Approved

#470 feat: sort transactions better
  src/app-gocardless/tests/utils.spec.js
  src/app-gocardless/utils.js
  upcoming-release-notes/470.md
Labels: :white_check_mark: Approved

#432 integrate FileService for app-sync.js
  src/app-simplefin/app-simplefin.js
  src/app-sync.js
  src/app-sync.test.js
  src/app-sync/errors.js
  src/app-sync/services/files-service.js
  src/app-sync/tests/services/files-service.test.js
  src/app-sync/validation.js
  src/util/middlewares.js
  upcoming-release-notes/432.md
Labels: :white_check_mark: Approved

#482 Do not request transactions when listing accounts
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/482.md
Labels: :white_check_mark: Approved

#487 🐛 Fix migrations not working on fresh clone
  app.js
  upcoming-release-notes/487.md
Labels: :white_check_mark: Approved

#486 Update easybank-bawaatww.js to change accessValidForDays: 179 from 180
  src/app-gocardless/banks/easybank-bawaatww.js
  upcoming-release-notes/486.md
Labels: :white_check_mark: Approved

#483 Only pull single account data from SimpleFIN if syncing one account
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/483.md
Labels: :white_check_mark: Approved
