Repository actualbudget/actual-server, pull requests merged in 2024-11, with the labels that each got.

#492 🔖 (24.11.0)
  package.json
  upcoming-release-notes/432.md
  upcoming-release-notes/470.md
  upcoming-release-notes/473.md
  upcoming-release-notes/474.md
  upcoming-release-notes/478.md
  upcoming-release-notes/480.md
  upcoming-release-notes/481.md
  upcoming-release-notes/482.md
  upcoming-release-notes/483.md
  upcoming-release-notes/486.md
  upcoming-release-notes/487.md
Labels: :white_check_mark: Approved

#495 [WIP] Update yarn.lock file
  yarn.lock
Labels: :construction: WIP

#485 Check SimpleFIN access key format
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/485.md
Labels: :white_check_mark: Approved

#479 build: bump docker image base, set node_env=prod
  Dockerfile
  docker/edge-alpine.Dockerfile
  docker/edge-ubuntu.Dockerfile
  docker/stable-alpine.Dockerfile
  docker/stable-ubuntu.Dockerfile
  upcoming-release-notes/479.md
Labels: :white_check_mark: Approved

#490 Add support for SWEDBANK_HABALV22 transaction date
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/swedbank-habalv22.js
  src/app-gocardless/banks/tests/swedbank-habalv22.spec.js
  upcoming-release-notes/490.md
Labels: :white_check_mark: Approved

#497 Enrich pending transaction creditor info for SWEDBANK_HABALV22
  src/app-gocardless/banks/swedbank-habalv22.js
  src/app-gocardless/banks/tests/swedbank-habalv22.spec.js
  upcoming-release-notes/497.md
Labels: :white_check_mark: Approved

#493 `ING_PL_INGBPLPW` should prefer valueDate over bookingDate
  src/app-gocardless/banks/ing-pl-ingbplpw.js
  upcoming-release-notes/493.md
Labels: :white_check_mark: Approved

#504 fix bug in batch SimpleFIN startDate logic
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/504.md
Labels: :white_check_mark: Approved

#498 OpenID
  jest.global-setup.js
  migrations/1718889148000-openid.js
  migrations/1719409568000-multiuser.js
  package.json
  src/account-db.js
  src/accounts/openid.js
  src/accounts/password.js
  src/app-account.js
  src/app-admin.js
  src/app-admin.test.js
  src/app-gocardless/app-gocardless.js
  src/app-openid.js
  src/app-secrets.js
  src/app-sync.js
  src/app-sync.test.js
  src/app-sync/services/files-service.js
  src/app-sync/tests/services/files-service.test.js
  src/app.js
  src/config-types.ts
  src/load-config.js
  src/scripts/reset-password.js
  src/services/user-service.js
  src/util/middlewares.js
  src/util/validate-user.js
  tsconfig.json
  upcoming-release-notes/498.md
  yarn.lock
Labels: :mag: Ready for review

#507 🐛 Fix existing sessions when using the latest version with Openid
  migrations/1719409568000-multiuser.js
  src/account-db.js
  src/accounts/openid.js
  src/app-account.js
  upcoming-release-notes/507.md
Labels: :white_check_mark: Approved

#511 Fix Hype Bank sync (`HYPE_HYEEIT22`)
  src/app-gocardless/bank-factory.js
  upcoming-release-notes/511.md
Labels: :mag: Ready for review
