Repository actualbudget/actual-server, pull requests merged in 2024-05, with the labels that each got.

#351 :bookmark: (24.5.0) mobile improvements and much more
  package.json
  upcoming-release-notes/333.md
  upcoming-release-notes/334.md
  upcoming-release-notes/341.md
  upcoming-release-notes/342.md
  upcoming-release-notes/343.md
  upcoming-release-notes/345.md
  yarn.lock
Labels: ✅ Approved

#346 Add gocardless support for Sparkasse Karlsruhe (Germany)
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/spk-karlsruhe-karsde66.js
  upcoming-release-notes/346.md
Labels: 🔍 Ready for Review

#350 Extend bank adapter for SEB Kort
  src/app-gocardless/banks/seb-kort-bank-ab.js
  upcoming-release-notes/350.md
Labels: 🔍 Ready for Review

#312 Added Header Authentication - Server Part
  src/account-db.js
  src/app-account.js
  src/config-types.ts
  src/load-config.js
  src/util/validate-user.js
  upcoming-release-notes/312.md
Labels: 🔍 Ready for Review

#355 Add BANKS_WITH_LIMITED_HISTORY constant and Implement BANKINTER_BKBKESMM Bank Adapter
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/bankinter-bkbkesmm.js
  src/app-gocardless/services/gocardless-service.js
  upcoming-release-notes/355.md
Labels: ✅ Approved

#349 fill in creditor name for BNP bank transactions
  src/app-gocardless/banks/bnp-be-gebabebb.js
  upcoming-release-notes/349.md
Labels: 🔍 Ready for Review, ✅ Approved
