Repository actualbudget/actual-server, pull requests merged in 2024-07, with the labels that each got.

#383 :bookmark: (24.7.0) custom reports, splits in rules, tags and more
  package.json
  upcoming-release-notes/359.md
  upcoming-release-notes/360.md
  upcoming-release-notes/362.md
  upcoming-release-notes/366.md
  upcoming-release-notes/367.md
  upcoming-release-notes/370.md
  upcoming-release-notes/372.md
  upcoming-release-notes/375.md
  upcoming-release-notes/376.md
  upcoming-release-notes/378.md
  upcoming-release-notes/380.md
  yarn.lock
Labels: 🔍 Ready for Review

#386 Prettify GoCardless Bank Integration README
  src/app-gocardless/README.md
  src/app-gocardless/banks/sandboxfinance-sfin0000.js
  src/app-gocardless/banks/spk-karlsruhe-karsde66.js
  upcoming-release-notes/386.md
Labels: 🔍 Ready for Review

#385 Update URL to log into SimpleFIN.
  src/app-simplefin/app-simplefin.js
  upcoming-release-notes/385.md
Labels: 🔍 Ready for Review

#390 Remove trafico in favor of our community bot
  .github/workflows/trafico.yml
  upcoming-release-notes/390.md
Labels: 🔍 Ready for Review

#391 Update SEB Credit Card adapter to include SEB Card Accounts
  src/app-gocardless/banks/seb-kort-bank-ab.js
  upcoming-release-notes/391.md
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#353 Move bank sync payee name normalisation from `actual` to `actual-server`
  src/app-gocardless/banks/abanca-caglesmm.js
  src/app-gocardless/banks/american-express-aesudef1.js
  src/app-gocardless/banks/bankinter-bkbkesmm.js
  src/app-gocardless/banks/belfius_gkccbebb.js
  src/app-gocardless/banks/bnp-be-gebabebb.js
  src/app-gocardless/banks/danskebank-dabno22.js
  src/app-gocardless/banks/ing-ingddeff.js
  src/app-gocardless/banks/ing-pl-ingbplpw.js
  src/app-gocardless/banks/integration-bank.js
  src/app-gocardless/banks/mbank-retail-brexplpw.js
  src/app-gocardless/banks/nationwide-naiagb21.js
  src/app-gocardless/banks/norwegian-xx-norwnok1.js
  src/app-gocardless/banks/sandboxfinance-sfin0000.js
  src/app-gocardless/banks/seb-kort-bank-ab.js
  src/app-gocardless/banks/seb-privat.js
  src/app-gocardless/banks/sparnord-spnodk22.js
  src/app-gocardless/banks/spk-karlsruhe-karsde66.js
  src/app-gocardless/banks/spk-marburg-biedenkopf-heladef1mar.js
  src/app-gocardless/services/tests/gocardless-service.spec.js
  src/app-simplefin/app-simplefin.js
  src/util/payee-name.js
  src/util/title/index.js
  src/util/title/lower-case.js
  src/util/title/specials.js
  upcoming-release-notes/353.md
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#389 add Fortuneo Banque GoCardless integration
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/FORTUNEO_FTNOFRP1XXX.js
  src/app-gocardless/banks/tests/FORTUNEO_FTNOFRP1XXX.spec.js
  upcoming-release-notes/389.md
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#396 Add gocardless support for easybank (Austria)
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/bank.interface.ts
  src/app-gocardless/banks/easybank-bawaatww.js
  src/app-gocardless/banks/tests/easybank-bawaatww.spec.js
  upcoming-release-notes/396.md
Labels: :white_check_mark: Approved

#400 Fix `verify` script
  package.json
  upcoming-release-notes/400.md
Labels: :white_check_mark: Approved

#401 Added GoCardless Integration for ING (Romania)
  src/app-gocardless/bank-factory.js
  src/app-gocardless/banks/ing-ingbrobu.js
  upcoming-release-notes/401.md
Labels: :white_check_mark: Approved

#403 ⬆️ upgrade yarn to 4.3.1
  .yarn/releases/yarn-4.0.1.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  package.json
  upcoming-release-notes/403.md
  yarn.lock
Labels: :white_check_mark: Approved

#402 Obfuscate password when login the login header
  src/app-account.js
  upcoming-release-notes/402.md
Labels: :white_check_mark: Approved

#406 fix date calculation in Nationwide bank handler
  src/app-gocardless/banks/nationwide-naiagb21.js
  upcoming-release-notes/406.md
Labels: :white_check_mark: Approved
